### ISSUE TITLE
Vagrant up fails provisioning

### ISSUE THREAD

**Issue by clayheaton** [Scifabric/pybossa#1965]
I see this is the subject of several recent pull requests. 

@teleyinex and @cerquide I just tried a clean install of Pybossa from

```
commit e94f3c6c16a2edc3889a6b415737193e961bb8c2 (HEAD -> master, tag: v3.1.2, origin/master, origin/HEAD)
Merge: 9aa4d75e d718b5ee
Author: Daniel Lombraña González <teleyinex@gmail.com>
Date:   Sun Feb 2 20:46:43 2020 +0100

    Merge pull request #1963 from Scifabric/sqlalchemy-1.3.0

    chore: increase SQLAlachemy version.
```

The `vagrant up` command failed during provisioning when trying to install `jeepney`. This was the error. 

```
default: TASK [install PyBossa virtualenv packages, can take some time...] **************
    default: fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/home/vagrant/pybossa-env/bin/pip install -r /vagrant/requirements.txt", "failed": true, "msg": "stdout: Looking in indexes: https://pypi.python.org/simple/\nObtaining file:///vagrant (from -r /vagrant/requirements.txt (line 3))\nCollecting alembic==0.9.10\n  Using cached alembic-0.9.10.tar.gz (1.0 MB)\nCollecting arrow==0.12.1\n  Using cached arrow-0.12.1.tar.gz (65 kB)\nCollecting asn1crypto==0.24.0\n  Using cached asn1crypto-0.24.0-py2.py3-none-any.whl (101 kB)\nCollecting Babel==2.6.0\n  Using cached Babel-2.6.0-py2.py3-none-any.whl (8.1 MB)\nCollecting beautifulsoup4==4.7.0\n  Using cached beautifulsoup4-4.7.0-py2-none-any.whl (94 kB)\nCollecting blinker==1.4\n  Using cached blinker-1.4.tar.gz (111 kB)\nCollecting certifi==2018.11.29\n  Using cached certifi-2018.11.29-py2.py3-none-any.whl (154 kB)\nCollecting cffi==1.11.5\n  Using cached cffi-1.11.5-cp27-cp27mu-manylinux1_x86_64.whl (407 kB)\nCollecting chardet==3.0.4\n  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)\nCollecting Click==7.0\n  Using cached Click-7.0-py2.py3-none-any.whl (81 kB)\nCollecting colorama==0.4.1\n  Using cached colorama-0.4.1-py2.py3-none-any.whl (15 kB)\nCollecting cov-core==1.15.0\n  Using cached cov-core-1.15.0.tar.gz (5.9 kB)\nCollecting coverage==4.5.2\n  Using cached coverage-4.5.2-cp27-cp27mu-manylinux1_x86_64.whl (201 kB)\nCollecting croniter==0.3.28\n  Using cached croniter-0.3.28-py2.py3-none-any.whl (16 kB)\nCollecting cryptography>=2.4.2\n  Using cached cryptography-2.8-cp27-cp27mu-manylinux2010_x86_64.whl (2.3 MB)\nCollecting cssselect==1.0.3\n  Using cached cssselect-1.0.3-py2.py3-none-any.whl (16 kB)\nCollecting debtcollector==1.20.0\n  Using cached debtcollector-1.20.0-py2.py3-none-any.whl (18 kB)\nCollecting decorator==4.3.0\n  Using cached decorator-4.3.0-py2.py3-none-any.whl (9.2 kB)\nCollecting entrypoints==0.2.3\n  Using cached entrypoints-0.2.3-py2.py3-none-any.whl (9.4 kB)\nCollecting factory-boy==2.4.1\n  Using cached factory_boy-2.4.1.tar.gz (78 kB)\nCollecting Faker==1.0.1\n  Using cached Faker-1.0.1-py2.py3-none-any.whl (845 kB)\nCollecting feedparser==5.2.1\n  Using cached feedparser-5.2.1.tar.bz2 (192 kB)\nCollecting Flask==1.0.2\n  Using cached Flask-1.0.2-py2.py3-none-any.whl (91 kB)\nCollecting Flask-Assets==0.12\n  Using cached Flask-Assets-0.12.tar.gz (22 kB)\nCollecting Flask-Babel==0.9\n  Using cached Flask-Babel-0.9.tar.gz (38 kB)\nCollecting Flask-Cors==3.0.2\n  Using cached Flask_Cors-3.0.2-py2.py3-none-any.whl (15 kB)\nCollecting Flask-DebugToolbar==0.10.1\n  Using cached Flask_DebugToolbar-0.10.1-py2.py3-none-any.whl (326 kB)\nCollecting Flask-HTTPAuth==3.2.4\n  Using cached Flask_HTTPAuth-3.2.4-py2.py3-none-any.whl (3.8 kB)\nCollecting flask-json-multidict==1.0.0\n  Using cached flask_json_multidict-1.0.0.tar.gz (10 kB)\nCollecting Flask-Login==0.4.1\n  Using cached Flask-Login-0.4.1.tar.gz (14 kB)\nCollecting Flask-Mail==0.9.1\n  Using cached Flask-Mail-0.9.1.tar.gz (45 kB)\nCollecting Flask-Misaka==0.3.0\n  Using cached Flask-Misaka-0.3.0.tar.gz (168 kB)\nCollecting Flask-OAuthlib==0.9.1\n  Using cached Flask_OAuthlib-0.9.1-py2.py3-none-any.whl (38 kB)\nCollecting Flask-Plugins==1.6.1\n  Using cached Flask-Plugins-1.6.1.tar.gz (10 kB)\nCollecting flask-profiler==1.6\n  Using cached flask_profiler-1.6.tar.gz (327 kB)\nCollecting Flask-SimpleLDAP==1.1.2\n  Using cached Flask-SimpleLDAP-1.1.2.tar.gz (4.6 kB)\nCollecting Flask-SQLAlchemy==2.3.2\n  Using cached Flask_SQLAlchemy-2.3.2-py2.py3-none-any.whl (16 kB)\nCollecting Flask-WTF>=0.9.5\n  Using cached Flask_WTF-0.14.2-py2.py3-none-any.whl (14 kB)\nCollecting flatten-json==0.1.6\n  Using cached flatten_json-0.1.6.tar.gz (3.3 kB)\nCollecting google-api-python-client==1.5.5\n  Using cached google_api_python_client-1.5.5-py2.py3-none-any.whl (51 kB)\nCollecting html2text==2014.7.3\n  Using cached html2text-2014.7.3.tar.gz (32 kB)\nCollecting httplib2==0.12.0\n  Using cached httplib2-0.12.0.tar.gz (218 kB)\nCollecting humanize==0.5.1\n  Using cached humanize-0.5.1.tar.gz (14 kB)\nCollecting idna==2.8\n  Using cached idna-2.8-py2.py3-none-any.whl (58 kB)\nCollecting iiif-prezi>=0.2.9\n  Using cached iiif-prezi-0.3.0.tar.gz (27 kB)\nCollecting infinity==1.4\n  Using cached infinity-1.4.tar.gz (5.4 kB)\nCollecting intervals==0.8.1\n  Using cached intervals-0.8.1.tar.gz (15 kB)\nCollecting iso8601==0.1.12\n  Using cached iso8601-0.1.12-py2.py3-none-any.whl (12 kB)\nCollecting itsdangerous==1.1.0\n  Using cached itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)\n\n:stderr: DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support\nERROR: Could not find a version that satisfies the requirement jeepney==0.4 (from pybossa==3.1.2->-r /vagrant/requirements.txt (line 3)) (from versions: none)\nERROR: No matching distribution found for jeepney==0.4 (from pybossa==3.1.2->-r /vagrant/requirements.txt (line 3))\n"}
    default:
    default: PLAY RECAP *********************************************************************
```
