### ISSUE TITLE
vagrant up failed to populate DB

### ISSUE THREAD

**Issue by jroxendal** [Scifabric/pybossa#2001]
I want to try the vm as indicated by the docs, but get the following error when running `vagrant up` from the 

```
    default: TASK [populate PYBOSSA DB] *****************************************************
    default: fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/home/vagrant/pybossa-env/bin/python /vagrant/cli.py db_create", "msg": "[Errno 2] No such file or directory", "rc": 2}
    default: 	to retry, use: --limit @/vagrant/provisioning/playbook.retry
    default:
    default: PLAY RECAP *********************************************************************
    default: 127.0.0.1                  : ok=22   changed=14   unreachable=0    failed=1
```

It seems that `virtualenv_path: "/home/vagrant/pybossa-env"` should be `virtualenv_path: "/vagrant/pybossa-env"` in the playbook.

git HEAD is 
```
commit a770c0b0466288abaa4290cc0c0fe77f33aa98d1 (HEAD -> master, origin/master, origin/HEAD)
Author: Daniel Lombraña González <teleyinex@gmail.com>
Date:   Sat Oct 31 14:18:40 2020 +0100

    fix(doi): update the link to Zenodo DOI.
```
